# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  php74:
    docker:
      - image: circleci/php:7.4-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --no-suggest --prefer-source
      - run: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text
  php80:
    docker:
      - image: circleci/php:8.0-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --no-suggest --prefer-source
      - run: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text
workflows:
  version: 2
  build:
    jobs:
      - php74
      - php80
